apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ tpl .Values.initialEcrDockerConfigJson . | b64enc }}