replicaCount: 1


# 
# https://github.com/bitnami/charts/issues/18959
# https://github.com/docker-library/wordpress/pull/142
# https://developer.wordpress.org/advanced-administration/security/https/#using-a-reverse-proxy
