apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-wordpress
type: Opaque
data:
  rootpassword: "WEJYYVdzT0RCag=="
  password: "dU5LZG92VDZDVQ=="