apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-wordpress
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wordpress
      tier: {{ .Release.Name }}-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wordpress
        tier: {{ .Release.Name }}-frontend
    spec:
      containers:
      - image: {{ .Values.wordpress.image }}:{{ .Values.wordpress.tag }}
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Release.Name }}-mysql
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.mysql.db }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.mysql.user }}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql
              key: password
        - name: WORDPRESS_CONFIG_EXTRA
          value: {{- toYaml .Values.wordpress.configExtra | indent 10 }}
        ports:
        - containerPort: {{ .Values.wordpress.port }}
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-wordpress-claim
