apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-wordpress
spec:
  ports:
    - port: 3306
      name: mysql
  selector:
    app: {{ .Release.Name }}-wordpress
    tier: {{ .Release.Name }}-mysql